language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
deploy:
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: ostapsteam
    password:
      secure: DbtB67STFVjinuuF062TLixr53ffGaO0BFcp/zshyWqM4QAar/AwGrd2iEgRGheJM8awSMxZQOYWC14syFoeSrz7xLOFkm5BCG2YbR/4RSR7Mwoob7+cl4w+8fiOuMO7MkalF3M/vEMtuUo5pj22e19AJMNNJ82rAEQlGv5C5C1uWuDDrbwR9IX7ffY/kLjO9fZxVrTyKRTE2E+p8EJpYyElzEHyaKROjZpoWDWj3hoBG5f1fjL73XqRLQarNF6jkd37oEhKipVUndfBIgTcwPfJ+6olbCgs8G2JAS/83fffcFEo3GWHSwrXH9esR6GPyvo3ykstAPafjtas+8DH15Ur/b6Lnymih/Lmmyw6pf5ypfz0pE9bV6JdtebTb6E/g+a0TOnlPkyLhpYvhNO+w7S5LSTcnDBjknQ1t6v1zBFZmGyrwDfRbaHhRRK+mjxVGwUvKm56enVLGnZCBhzFgfkofDLVIdnpQMPX/4j1KpmiGviiKpQwuQIA+njrnFIPgaZ89BbQgdLl+NEn5NjHSeXX6ashcP+H27Y432lkLNbN2Sl6jfatTVmA/aHHTZg+XDMU1rVmVLoHSVJhz3RVtZmvXAXVuFmrvBIvUPy6lon2oaEt69oCZeQ4XwTQu55irZBXu1h1Z+Kr04NhaeNFeUs68tXIIf9RNAoWiGwWFEo=
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6"